### ISSUE TITLE
Attach-BaselineGroup missing

### ISSUE THREAD

**Issue by smokinbanz** [TheDotSource/VUMXtra#1]
Great job with this, very excited about it since VMware hasn't addressed it!
The article here: https://thedotsource.com/2019/04/01/vum-extra-module-automating-baseline-groups-and-more/

Shows that attach-baselinegroup is a cmdlet but it is not available in the download. Any chance we can get that added into the module?

**Comment by TheDotSource** [comment]
Hello, sorry for the late reply!

Please have a look at the 1.1 update blog post here:

https://thedotsource.com/2020/01/07/vumxtra-1-1-update/

This CMDlet has changed to Add-EntityBaselineGroup to make it compliant with PowerShell approved verbs, and to make it more consistent with the other VMware VUM CMDlets.

Let me know if you have any other issues!
