### ISSUE TITLE
Updating this package to provide functionality to configure vLCM

### ISSUE THREAD

**Issue by vishalvisd** [TheDotSource/VUMXtra#4]
I know the intension of this package is to automate the VUM configuration, but with vSphere 7, which replaces VUM with vLCM and as I tried to use this package to upload the updates, it was uploading but the updates were not visible on the "Image Depot" tab with vLCM.
With the effort that has been put in bringing this package, it will be a great if this package adds the ability to configure vLCM as well.

**Comment by TheDotSource** [comment]
Unfortunately LCM is a completely different product and API so would be out of scope for this module. LCM has a fairly comprehensive REST API so all automation should be possible via this.
