### ISSUE TITLE
Problem when Processing Multiple hosts in Loop

### ISSUE THREAD

**Issue by cryton2707** [TheDotSource/VUMXtra#8]
If you have a foreach and a group of hosts.  There is a bug in that if one of the hosts has already been remediated then the function breaks out the script completely. 

Calling 
Update-EntityBaselineGroup -BaselineGroupName $baselineGroup -Entity $VMHost -confirm:$false

if entity $vmhost has been patched already then the next host isnt processed. 

Solution is to change the **Break** to a **Return** at line _219_ in Return Update-EntityBaselineGroup

**Comment by TheDotSource** [comment]
You are correct, a return would be more appropriate at this point. Would you mind creating a PR?

**Comment by TheDotSource** [comment]
Resolved in #9
